# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_bSpline_fit <- function(x, y, df, degree, internal_knots, boundary_knots) {
    .Call('_example_pkg_Rcpp_splines2_rcpp_bSpline_fit', PACKAGE = 'example.pkg.Rcpp.splines2', x, y, df, degree, internal_knots, boundary_knots)
}

